### ISSUE TITLE
ImportError: No module named lib.label_map_util

### ISSUE THREAD

**Issue by Rohan-Kumar** [KleinYuan/tf-object-detection#1]
Getting this error when i run app.py

**Comment by KleinYuan** [comment]
@Rohan-Kumar Ohhh shooot. Forgot to add it. 
Last commit fix this.

Try again.

**Comment by Rohan-Kumar** [comment]
Weird! I'm getting this error now
 File "tf-object-detection\lib\label_map_util.py", line 22, in <module>
    import string_int_label_map_pb2
ImportError: No module named 'string_int_label_map_pb2'

I know that it is present but still it's showing this.

**Comment by KleinYuan** [comment]
@Rohan-Kumar Could you pull the updated master branch and try again?

I try it in multiple envs and all works.

**Comment by Rohan-Kumar** [comment]
Yeah worked fine on my friend's mac. Maybe something wrong with my windows laptop :p

**Comment by aby03** [comment]
Can i use it on python 3?
When i run on python 3 after changing print in object_detection.py initially it showed this error

File "tf-object-detection\lib\label_map_util.py", line 22, in
import string_int_label_map_pb2
ImportError: No module named 'string_int_label_map_pb2'

To fix it, I changed this line in object_detection.py
import label_map_util
to
import lib.label_map_util

and in label_map_util.py
import string_int_label_map_pb2
to
from lib import string_int_label_map_pb2

NOW I HAVE FOLLOWING PROBLEM

  File "/tf-object-detection-master/models/object_detection.py", line 122, in predict
    for i in range(0, num_detections):

TypeError: only integer scalar arrays can be converted to a scalar index

I am using model number 2 ie ssd_inception_v2_coco_11_06_2017 and getting no detections on test image.
Any help is appreciated in running it for python 3
