### ISSUE TITLE
wow，amazing, your code is so clean and tidy ,and i can understand it .

### ISSUE THREAD

**Issue by mathCrazyy** [KleinYuan/tf-object-detection#2]
yesterday I wrote a videocapture, and It is so slow, I can not real time to detect object , my machine i3, I did not have a test on i7.and can you have a realtime detection, thank you.

**Comment by mathCrazyy** [comment]
e...I see you speed up it 10%-20%,so..i cant prevent me to contant with you , I am really interesting to it .

**Comment by KleinYuan** [comment]
@mathCrazyy 
Also did a bunch of optimizations like graph, session management since your yesterday's fork.

At least, on i7, you can run a relatively smooth SSD-MobileNet model, like 6-8 FPS.

Not quite sure about i3 tho.

**Comment by mathCrazyy** [comment]
I tried it ,the model is ssd_mobilenet_v1_coco_11_06_2017, isnot it ? got the image through the camera, but it is slow, about need 2 seconds to process one image , the size of images is 640*480. can you realtime when processing the camera images?

**Comment by mathCrazyy** [comment]
um, so I also need to change other code ,right? I only changed the predict function to apply the early code just now, the parameter was one . so sad ,what shoud we do to achieve a realtime performance , after all ,reputedly, mobilenet can do it.

**Comment by KleinYuan** [comment]
@mathCrazyy did you pull the most updated master branch?

**Comment by mathCrazyy** [comment]
your execution force are so  powerful, I test it just now, at my laptop, 7700k,1050ti，8g memory，,although your code display that 7-8fps,but it looks very smooth, in addition, CPU occupancy rate is 100%, memory occupancy rate is about 57%. I paid attention to other issue just now ,I also want to use my own data to train, thank you very much for you let me see this way is feasible.

**Comment by KleinYuan** [comment]
Glad to hear that.

**Comment by sumesh107** [comment]
Hey how many object classes does this detect ?

**Comment by aaronhan92** [comment]
Hi, I'm new to deep learning. May i know are you using OpenCV native function for object detection and then pass the output result to do classification? Or your object detection is end to end trainable (like Faster RCNN, YOLO etc)?
