### ISSUE TITLE
Train in my own dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [KleinYuan/tf-object-detection#3]
How can I train in my own dataset?

**Comment by KleinYuan** [comment]
You can check tensorflow/models and navigate to object detection for more details on training.

In here, I only put inference scripts.

@Zumbalamambo

**Comment by KleinYuan** [comment]
Due to lack of follow up and this is not really an issue we try to resolve here, I will close it for now. If you have futher questions, please reopen it.
