### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by NikAndrush** [KleinYuan/tf-object-detection#5]
i have this error when i run sudo python app.py
i added the line:    Defaults env_keep="DISPLAY XAUTHORITY" at the end of visudo but i still have this error

**Comment by KleinYuan** [comment]
That seems something wrong with your pc libs. It seems not related to this project however, if you provide more information, I may be able to help u.

**Comment by KleinYuan** [comment]
Close due to lack of followup and seems more like a pc setup rather than repo issue.
Please reopen it if necessary.
