### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by aby03** [KleinYuan/tf-object-detection#6]
Can i use it on python 3?
When i run on python 3 after changing print in object_detection.py initially it showed this error

File "tf-object-detection\lib\label_map_util.py", line 22, in
import string_int_label_map_pb2
ImportError: No module named 'string_int_label_map_pb2'

To FIX it, I changed this line in object_detection.py
import label_map_util
to
import lib.label_map_util

and in label_map_util.py
import string_int_label_map_pb2
to
from lib import string_int_label_map_pb2

NOW I HAVE FOLLOWING PROBLEM

File "/tf-object-detection-master/models/object_detection.py", line 122, in predict
for i in range(0, num_detections):

TypeError: only integer scalar arrays can be converted to a scalar index

I am using model number 2 ie ssd_inception_v2_coco_11_06_2017 and getting no detections on test image.
Any help is appreciated in running it for python 3

**Comment by aby03** [comment]
Thanks works now. It was problem of data type of num_detections.
Using it with IP Camera. Great results. Thanks.

**Comment by aaronhan92** [comment]
What data type did you used?
