### ISSUE TITLE
Tensorflow Object Detection API

### ISSUE THREAD

**Issue by gburnett-nvidia** [KleinYuan/tf-object-detection#8]
Hey, I think this needs the Tensorflow Object Detection API as a dependency as well. Can you include instructions on how to install that?

**Comment by KleinYuan** [comment]
@garylburnett 
Hi, this repo does not use `Tensorflow Object Detection API ` as dependency. You can just follow the readme and run it.

All it does is just load graph and run the tf

**Comment by KleinYuan** [comment]
Just follow the [README](https://github.com/KleinYuan/tf-object-detection#run-demo) and if you still can not run it, please reopen the issue.
