### ISSUE TITLE
No module named 'string_int_label_map_pb2

### ISSUE THREAD

**Issue by taehee33** [KleinYuan/tf-object-detection#9]
python app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from models import object_detection
  File "/home/kmh/Desktop/han/obj/t1/tf-object-detection/models/object_detection.py", line 7, in <module>
    import lib.label_map_util
  File "/home/kmh/Desktop/han/obj/t1/tf-object-detection/lib/label_map_util.py", line 22, in <module>
    import string_int_label_map_pb2
ImportError: No module named 'string_int_label_map_pb2'

i got an issue 
icant handle this problem 
what do i do?

**Comment by KleinYuan** [comment]
Seems you got an issue on PYTHONPATH

how did u run it?
Via any IDE or through terminal?

If u are running purely with terminal,
Try navigate to the root folder of this repo then:

export PYTHONPATH=.

**Comment by WynMew** [comment]
@taehee33 

try this:

in line 22 of label_map_util.py: import lib.string_int_label_map_pb2
in line 105 of label_map_util.py: label_map = lib.string_int_label_map_pb2.StringIniLabelMap()
